<?php

namespace MainBundle\Repository;

/**
 * BannissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannissementRepository extends \Doctrine\ORM\EntityRepository
{
}
