<?php

namespace MainBundle\Repository;

/**
 * IllustrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IllustrationRepository extends \Doctrine\ORM\EntityRepository
{
}
